export DJANGO_SETTINGS_MODULE=api.settings
export PYTHONUNBUFFERED=1
export DATABASE_NAME=mbpt
export DATABASE_HOST=127.0.0.1
export DATABASE_PORT=3306
export DATABASE_PASSWORD=root
export DATABASE_USER=root