# Generated by Django 2.0.4 on 2018-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.URLField(),
        ),
    ]
