# Generated by Django 2.0.4 on 2018-04-26 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('image', models.URLField(blank=True)),
                ('default_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.Language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Tier')),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Todo')),
            ],
        ),
    ]
