# Generated by Django 2.0.4 on 2018-04-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(blank=None, null=True, to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tier',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Tier'),
        ),
    ]
