# Generated by Django 2.0.4 on 2018-04-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20180425_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='challenges.SubmissionStatus'),
        ),
    ]
